apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconf
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 8080;

        location / {
          proxy_pass http://go-hostname.backend.svc.cluster.local:80;
        }
      }
    }
---
apiVersion: nginx.tsuru.io/v1alpha1
kind: Nginx
metadata:
  name: waf
spec:
  replicas: 1
  config:
    kind: ConfigMap
    name: nginxconf
  service:
    type: NodePort

